import type { Alert, Evaluation, FeatureImportance, InferenceModelInfo, InferenceResult, ModelMetric } from "./types";

export const sampleAlerts: Alert[] = [
  {
    alert_id: "alert-evt-001",
    timestamp: "2026-06-03T08:47:12Z",
    src_ip: "10.0.3.77",
    dst_ip: "10.0.0.5",
    attack_type: "Port Scan",
    severity: "Medium",
    confidence: 0.88,
    reason: "SYN packets to 120+ ports in under 30 seconds.",
    top_features: ["dst_port", "flow_packets_s", "syn_flag_count"],
    mitre_technique: "T1046 - Network Service Scanning",
    triage_priority: "P2",
  },
  {
    alert_id: "alert-evt-002",
    timestamp: "2026-06-03T09:02:05Z",
    src_ip: "192.168.1.45",
    dst_ip: "10.0.0.8",
    attack_type: "Brute Force",
    severity: "High",
    confidence: 0.94,
    reason: "80 failed login attempts against port 22.",
    top_features: ["failed_login_count", "dst_port", "flow_packets_s"],
    mitre_technique: "T1110 - Brute Force",
    triage_priority: "P1",
  },
  {
    alert_id: "alert-evt-003",
    timestamp: "2026-06-03T09:04:31Z",
    src_ip: "172.16.4.20",
    dst_ip: "10.0.0.12",
    attack_type: "DDoS",
    severity: "High",
    confidence: 0.92,
    reason: "High packet rate targeting web service.",
    top_features: ["flow_packets_s", "total_fwd_packets", "flow_bytes_s"],
    mitre_technique: "T1498 - Network Denial of Service",
    triage_priority: "P1",
  },
  {
    alert_id: "alert-evt-004",
    timestamp: "2026-06-03T09:15:44Z",
    src_ip: "10.0.5.33",
    dst_ip: "10.0.0.8",
    attack_type: "Brute Force",
    severity: "Medium",
    confidence: 0.79,
    reason: "Repeated SSH auth failures from new source.",
    top_features: ["failed_login_count", "dst_port", "flow_duration"],
    mitre_technique: "T1110 - Brute Force",
    triage_priority: "P2",
  },
  {
    alert_id: "alert-evt-005",
    timestamp: "2026-06-03T09:22:08Z",
    src_ip: "10.0.7.12",
    dst_ip: "10.0.0.15",
    attack_type: "Port Scan",
    severity: "Low",
    confidence: 0.71,
    reason: "Limited port sweep on non-critical host.",
    top_features: ["dst_port", "flow_packets_s", "syn_flag_count"],
    mitre_technique: "T1046 - Network Service Scanning",
    triage_priority: "P3",
  },
];

export const fallbackEvaluation: Evaluation = {
  model_name: "RuleBasedBaseline",
  sample_count: 5,
  accuracy: 1,
  attack_recall: 1,
  benign_recall: 1,
};

export const fallbackModelMetrics: ModelMetric[] = [
  {
    model_name: "decision_tree",
    dataset_id: "cicids2017-full",
    accuracy: 0.99874,
    precision: 0.99683,
    recall: 0.99676,
    f1_score: 0.99680,
    false_positive_rate: 0.00078,
  },
  {
    model_name: "random_forest",
    dataset_id: "cicids2017-full",
    accuracy: 0.99888,
    precision: 0.99721,
    recall: 0.99712,
    f1_score: 0.99717,
    false_positive_rate: 0.00068,
  },
  {
    model_name: "logistic_regression",
    dataset_id: "cicids2017-full",
    accuracy: 0.90134,
    precision: 0.87127,
    recall: 0.58570,
    f1_score: 0.70050,
    false_positive_rate: 0.02123,
  },
  {
    model_name: "logistic_regression_scaled",
    dataset_id: "unsw-nb15-official",
    accuracy: 0.7326,
    precision: 0.7416,
    recall: 0.7894,
    f1_score: 0.7647,
    false_positive_rate: 0.3371,
  },
  {
    model_name: "random_forest",
    dataset_id: "unsw-nb15-official",
    accuracy: 0.5741,
    precision: 0.6626,
    recall: 0.4614,
    f1_score: 0.5440,
    false_positive_rate: 0.2879,
  },
  {
    model_name: "xgboost",
    dataset_id: "unsw-nb15-official",
    accuracy: 0.5294,
    precision: 0.5975,
    recall: 0.4453,
    f1_score: 0.5103,
    false_positive_rate: 0.3675,
  },
];

export const fallbackInferenceModel: InferenceModelInfo = {
  dataset_id: "cicids2017-full",
  model_name: "random_forest",
  model_path: "reports/pipeline/cicids2017-full/models/cicids2017-full-random_forest.joblib",
  available: false,
  status: "backend unavailable",
};

export const fallbackInferenceResult: InferenceResult = {
  dataset_id: "cicids2017-full",
  model_name: "random_forest",
  model_available: false,
  prediction: 1,
  prediction_label: "attack",
  confidence: 0.94,
  attack_probability: 0.94,
  top_features: [
    { feature: "Flow Bytes/s", importance: 0.0823 },
    { feature: "Flow Packets/s", importance: 0.0612 },
    { feature: "Total Fwd Packets", importance: 0.0431 },
    { feature: "Flow Duration", importance: 0.0387 },
    { feature: "SYN Flag Count", importance: 0.0215 },
  ],
  status: "demo fallback",
};
